/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;



/**
 *
 * @author youce
 */
public class SI extends javax.swing.JFrame {

    /**
     * Creates new form SI
     */
    
    public SI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ws = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ask = new javax.swing.JTextArea();
        Send = new javax.swing.JButton();
        Ad = new javax.swing.JButton();
        Ad1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 112, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(1060, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\youce\\Desktop\\ihm2\\IHM\\icons\\USTO.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USTO PLATFORME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 990, 140);

        ws.setBackground(new java.awt.Color(0, 102, 102));
        ws.setFont(new java.awt.Font("Georgia Pro", 1, 24)); // NOI18N
        ws.setForeground(new java.awt.Color(0, 102, 102));
        ws.setText("Welcome Dear Student");
        ws.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                wsAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(ws);
        ws.setBounds(360, 120, 330, 80);

        Ask.setColumns(20);
        Ask.setRows(5);
        jScrollPane1.setViewportView(Ask);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 520, 160);

        Send.setBackground(new java.awt.Color(0, 102, 102));
        Send.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Send.setForeground(new java.awt.Color(255, 255, 255));
        Send.setText("Send");
        Send.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        jPanel1.add(Send);
        Send.setBounds(410, 440, 140, 40);

        Ad.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Ad.setForeground(new java.awt.Color(0, 102, 102));
        Ad.setText("Check Answer's");
        Ad.setBorder(null);
        Ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdActionPerformed(evt);
            }
        });
        jPanel1.add(Ad);
        Ad.setBounds(440, 530, 220, 50);

        Ad1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Ad1.setForeground(new java.awt.Color(0, 102, 102));
        Ad1.setText("Acsses Document's");
        Ad1.setBorder(null);
        Ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ad1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ad1);
        Ad1.setBounds(730, 530, 220, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Ask Question ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 230, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_wsAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_wsAncestorAdded

   

 
    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
       // Get the message from the text area in SI
    
    
    }//GEN-LAST:event_SendActionPerformed

    private void AdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdActionPerformed
        // TODO add your handling code here:
         this.dispose();
          Answers AnswersFrame = new Answers();
        AnswersFrame.setVisible(true);
        AnswersFrame.pack();
         AnswersFrame.setLocationRelativeTo(null);
     
    }//GEN-LAST:event_AdActionPerformed

    private void Ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ad1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
          Document DocumentFrame = new Document();
        DocumentFrame.setVisible(true);
        DocumentFrame.pack();
         DocumentFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_Ad1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ad;
    private javax.swing.JButton Ad1;
    private javax.swing.JTextArea Ask;
    private javax.swing.JButton Send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ws;
    // End of variables declaration//GEN-END:variables
}
